//------------------------------------------------------------------------
// Copyright(c) 2025 Paul Ursulean.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"NotationChordHelper.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"NotationChordHelper VST3 (64Bit)"
#else
#define stringFileDescription	"NotationChordHelper VST3"
#endif
#define stringCompanyName		"Paul Ursulean\0"
#define stringLegalCopyright	"Copyright(c) 2025 Paul Ursulean."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
