name: Build and Release VST3 Plugin

on:
  push:
    tags:
      - 'v*' # Trigger on version tags like v1.0.0

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1.14
      with:
        cmake-version: '4.0.2'

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release

    - name: Create Windows release zip
      run: |
        mkdir -p release
        powershell Compress-Archive -Path "build/VST3/Release/NotationChordHelper.vst3" -DestinationPath "release/NotationChordHelper-Windows.zip"

    - name: Upload Windows artifacts
      uses: actions/upload-artifact@v4
      with:
        name: NotationChordHelper-Windows
        path: release/NotationChordHelper-Windows.zip

  build-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1.14
      with:
        cmake-version: '4.0.2'

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release

    - name: Create macOS release zip
      run: |
        mkdir -p release
        cd build/VST3/Release
        zip -r ../../../release/NotationChordHelper-macOS.zip NotationChordHelper.vst3

    - name: Upload macOS artifacts
      uses: actions/upload-artifact@v4
      with:
        name: NotationChordHelper-macOS
        path: release/NotationChordHelper-macOS.zip

  create-release:
    needs: [build-windows, build-macos]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Download Windows artifacts
      uses: actions/download-artifact@v4
      with:
        name: NotationChordHelper-Windows
        path: release/

    - name: Download macOS artifacts
      uses: actions/download-artifact@v4
      with:
        name: NotationChordHelper-macOS
        path: release/

    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          release/NotationChordHelper-Windows.zip
          release/NotationChordHelper-macOS.zip
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 